---
title: "Homework 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(tidyverse)
library(kableExtra)
library(moments)
library(lubridate)
library(gridExtra)

```

#### Portfolio Management - Lubos
#### TXL

```{r}
# Annual returns
ret_ann = read.table("data/returns_annual.txt", skip = 5, header = TRUE) %>%
  rename(date = X.date) %>% data.table()
  

# Monthly returns
ret_mon = read.table("data/returns_monthly.txt", skip = 4, header = TRUE) %>% 
  data.table()
ret_mon$date = ymd(ret_mon$X.date)

# Daily returns
ret_daily = read.table("data/returns_daily.txt", skip = 5, header = TRUE) %>%
  data.table()
ret_daily$date = ymd(ret_daily$X.date)

```

## Means, Variances, and Standard Deviations
```{r}
# Bonds
rets = list(ret_ann, ret_mon, ret_daily)
period = list('Annual', 'Monthly', 'Daily')

stats_table = data.table()

stock_mean = c()
stock_var = c()
stock_sd = c()
stock_skew = c()
stock_kurt = c()

bond_mean = c()
bond_var = c()
bond_sd = c()
bond_skew = c()
bond_kurt = c()

corr = c()
covar = c()

for (i in 1:3) {
  d = rets[[i]]
  # Stocks
  stock_mean = stock_mean %>% c(mean(d$mktret))
  stock_var = stock_var %>% c(var(d$mktret))
  stock_sd = stock_sd %>% c(sd(d$mktret))
  stock_skew = stock_skew %>% c(skewness(d$mktret))
  stock_kurt = stock_kurt %>% c(kurtosis(d$mktret))
  
  # Bonds
  bond_mean = bond_mean %>% c(mean(d$bondret))
  bond_var = bond_var %>% c(var(d$bondret))
  bond_sd = bond_sd %>% c(sd(d$bondret))
  bond_skew = bond_skew %>% c(skewness(d$mktret))
  bond_kurt = bond_kurt %>% c(kurtosis(d$mktret))
  
  # Correlations
  corr = corr %>% c(cor(d$mktret, d$bondret))
  covar = covar %>% c(cov(d$mktret, d$bondret))
}

stock_table = data.table(period, stock_mean, stock_var, stock_sd, stock_skew, stock_kurt)
stock_table$Lower_CI = stock_table$stock_mean - 1.96 * stock_table$stock_sd
stock_table$Upper_CI = stock_table$stock_mean + 1.96 * stock_table$stock_sd

bond_table = data.table(period, bond_mean, bond_var, bond_sd, bond_skew, bond_kurt)
bond_table$Lower_CI = bond_table$bond_mean - 1.96 * bond_table$bond_sd
bond_table$Upper_CI = bond_table$bond_mean + 1.96 * bond_table$bond_sd
              
kable(stock_table) %>% kable_styling()
kable(bond_table) %>% kable_styling()

corr_table = data.table(period, covar, corr)
corr_table %>% kable() %>% kable_styling()
```

### Bar Graphs
```{r}
for (i in 1:3){
  d = rets[[i]]
  
   p1 = d %>% ggplot(aes(x = date, y = mktret)) +
     geom_bar(stat = 'identity', fill = 'darkblue') +
     ggtitle(paste0("Stock returns: ", period[i]))

  
   p2 = d %>% ggplot(aes(x = date, y = bondret)) +
     geom_bar(stat = 'identity', fill = 'darkred') + 
     ggtitle(paste0("Bond returns: ", period[i]))
   
   grid.arrange(p1, p2, ncol = 2)

   
}
```
### Histograms

```{r}
for (i in 1:3) {
  d = rets[[i]]
  p1 = d %>% ggplot(aes(x = mktret)) + 
    geom_histogram(bins = 40, fill = 'darkblue') +
    ggtitle(paste0("Stock returns historgram: ", period[i]))

  p2 = d %>% ggplot(aes(x = bondret)) + 
    geom_histogram(bins = 40, fill = 'darkred') + 
    ggtitle(paste0("Bond returns histogram: ", period[i]))

  grid.arrange(p1, p2, ncol = 2)

  
}
```


### Absolute Shortfall
```{r}
# Function to calculate shortfall 
shortfall = function(x, lvl) {
  total = length(x)
  under = sum(x < lvl)
  return(under/total)
}

lvls = seq(-.2, .2, .1)

# Based on observations
t = data.table(levels = lvls)

for (i in 1:3) {
  d = rets[[i]]
  t[, paste0("stock_", period[i])] = t$levels %>% 
    sapply(function(x){shortfall(d$mktret, x)})
}

for (i in 1:3) {
  d = rets[[i]]
  t[, paste0("bond_", period[i])] = t$levels %>% 
    sapply(function(x){shortfall(d$bondret, x)})

}

t %>% kable() %>% kable_styling()


# Based on normcdf
t2 = data.table(levels = lvls)
for (i in 1:3) {
  t2[, paste0("stock_", period[i])] = t$levels %>% 
    sapply(function(x) {pnorm(x, stock_mean[i], stock_sd[i])})
  
  p1 = t2 %>% ggplot(aes_string(x = "levels", y = paste0("stock_", period[i]))) +
    geom_line(color = 'darkblue', size = 2)
  
  t2[, paste0("bond_", period[i])] = t$levels %>%
    sapply(function(x) {pnorm(x, bond_mean[i], bond_sd[i])})
  
  p2 = t2 %>% ggplot(aes_string(x = "levels", y = paste0("bond_", period[i]))) + 
    geom_line(color = 'darkred', size = 2)

  grid.arrange(p1, p2, ncol = 2)
}

t2 %>% kable() %>% kable_styling()
  
```

### Stock Return vs Bond Return
```{r}

for (i in 1:3) {
  d = rets[[i]]
  mean_diff = mean(d$mktret - d$bondret)
  covar = var(d$mktret) + var(d$bondret) - 2 * cov(d$mktret, d$bondret)
  pval = pnorm(0, mean_diff, sqrt(covar))
  print(paste0(period[i], "_Pr(Rs < Rb): ", pval))

}

```